[SERVICE]
    Flush        1
    Daemon       Off
    Log_Level    info

[INPUT]
    Name         tail
    Path         /var/log/*.log
    Tag          app.logs
    Parser       json

[FILTER]
    Name         modify
    Match        app.logs
    Add          environment prod

[OUTPUT]
    Name         stdout
    Match        *
